development:
  adapter: mysql
  encoding: utf8
  database: sakerb_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: sakerb_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: sakerb_production
  username: root
  password: 
  host: localhost
